# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING, Callable, NamedTuple, TypeVar

from sila2.server import MetadataDict

from ..generated.powdercharacterizerdispenser import (
    AmbiguousDevice,
    Close_Responses,
    DeviceFault,
    DeviceNotConnected,
    IndexChamber_Responses,
    OperationCancelled,
    PowderCharacterizerDispenserBase,
    RunAllMotors_Responses,
    StopAll_Responses,
    Vibrate_Responses,
    VibrateWithAuger_Responses,
)
from ..drivers.powder_dispenser import (
    AmbiguousDeviceError,
    DeviceNotConnectedError,
    OperationCancelledError,
)

if TYPE_CHECKING:
    from ..server import Server
    from ..drivers.powder_dispenser import PowderCharacterizerDispenser


class _StepResult(NamedTuple):
    Success: bool
    StopReason: str
    ElapsedSec: float


_Result = TypeVar("_Result")


class PowderCharacterizerDispenserImpl(PowderCharacterizerDispenserBase):
    def __init__(
        self,
        parent_server: Server,
        driver: PowderCharacterizerDispenser,
    ) -> None:
        super().__init__(parent_server=parent_server)
        self._driver = driver

    @staticmethod
    def _step_result(result: dict) -> _StepResult:
        return _StepResult(
            Success=bool(result["success"]),
            StopReason=str(result["stop_reason"]),
            ElapsedSec=float(result["elapsed_sec"]),
        )

    @staticmethod
    def _call_driver(action: Callable[[], _Result]) -> _Result:
        """Translate expected hardware states into declared SiLA errors."""
        try:
            return action()
        except DeviceNotConnectedError as exc:
            raise DeviceNotConnected(str(exc)) from exc
        except AmbiguousDeviceError as exc:
            raise AmbiguousDevice(str(exc)) from exc
        except OperationCancelledError as exc:
            raise OperationCancelled(str(exc)) from exc
        except (OSError, RuntimeError) as exc:
            raise DeviceFault(str(exc)) from exc

    def get_Status(self, *, metadata: MetadataDict) -> str:
        return self._driver.status

    def IndexChamber(
        self, Pwm: int, MaxSeconds: float, Reverse: bool, *, metadata: MetadataDict
    ) -> IndexChamber_Responses:
        result = self._call_driver(
            lambda: self._driver.index_chamber(Pwm, MaxSeconds, Reverse)
        )
        return IndexChamber_Responses(Result=self._step_result(result))

    def Vibrate(self, Level: int, DurationSec: float, *, metadata: MetadataDict) -> Vibrate_Responses:
        self._call_driver(lambda: self._driver.vibrate(Level, DurationSec))
        return Vibrate_Responses()

    def VibrateWithAuger(self, Level: int, DurationSec: float, *, metadata: MetadataDict) -> VibrateWithAuger_Responses:
        self._call_driver(lambda: self._driver.vibrate_with_auger(Level, DurationSec))
        return VibrateWithAuger_Responses()

    def RunAllMotors(self, Level: int, DurationSec: float, *, metadata: MetadataDict) -> RunAllMotors_Responses:
        result = self._call_driver(
            lambda: self._driver.run_all_motors(Level, DurationSec)
        )
        return RunAllMotors_Responses(Result=self._step_result(result))

    def StopAll(self, *, metadata: MetadataDict) -> StopAll_Responses:
        self._driver.stop_all()
        return StopAll_Responses()

    def Close(self, *, metadata: MetadataDict) -> Close_Responses:
        self._driver.close()
        return Close_Responses()
