# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.powdercharacterizercamera_impl import PowderCharacterizerCameraImpl
from .generated.powdercharacterizercamera import PowderCharacterizerCameraFeature
from .drivers.camera import PowderCharacterizerCamera


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        driver: Optional[PowderCharacterizerCamera] = None,
    ):
        if name is None:
            name = "Powder Characterizer Camera Server"
        if description is None:
            description = "First-layer SiLA 2 camera server for Powder Characterizer."
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="PowderCharacterizerCamera",
            server_version="0.1",
            server_vendor_url="https://www.sekisui.com",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.driver = driver or PowderCharacterizerCamera()
        self.powdercharacterizercamera = PowderCharacterizerCameraImpl(self, self.driver)
        self.set_feature_implementation(PowderCharacterizerCameraFeature, self.powdercharacterizercamera)
