# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from datetime import timedelta
import json
from typing import TYPE_CHECKING

from sila2.server import MetadataDict, ObservableCommandInstanceWithIntermediateResponses

from ..generated.powdercharacterizer import (
    AbortCurrentOperation_Responses,
    CaptureCameraPreview_Responses,
    CaptureReposePreview_Responses,
    ClearClog_Responses,
    DiscardResults_Responses,
    GetArtifact_Responses,
    GetMaterialDatabase_Responses,
    GetSettings_Responses,
    PowderCharacterizerBase,
    RunAngleOfRepose_IntermediateResponses,
    RunAngleOfRepose_Responses,
    RunAutomatedExperiment_IntermediateResponses,
    RunAutomatedExperiment_Responses,
    RunBulkDensity_IntermediateResponses,
    RunBulkDensity_Responses,
    RunCalibration_IntermediateResponses,
    RunCalibration_Responses,
    RunManualExperiment_IntermediateResponses,
    RunManualExperiment_Responses,
    RunSingleTest_IntermediateResponses,
    RunSingleTest_Responses,
    RunTappedDensity_IntermediateResponses,
    RunTappedDensity_Responses,
    SaveResults_Responses,
    UpdateSettings_Responses,
)

if TYPE_CHECKING:
    from ..server import Server
    from ..application import PowderCharacterizerApplication


class PowderCharacterizerImpl(PowderCharacterizerBase):
    def __init__(
        self,
        parent_server: Server,
        application: PowderCharacterizerApplication,
    ) -> None:
        super().__init__(parent_server=parent_server)
        self._application = application

        # Default lifetime of observable command instances. Possible values:
        # None: Command instance is valid and stored in memory until server shutdown
        # datetime.timedelta: Command instance is deleted after this duration, can be increased during command runtime
        # Keep command instances available for browser reconnection well beyond
        # the expected experiment duration.
        self.RunAutomatedExperiment_default_lifetime_of_execution = timedelta(hours=24)
        self.RunCalibration_default_lifetime_of_execution = timedelta(hours=24)
        self.RunBulkDensity_default_lifetime_of_execution = timedelta(hours=24)
        self.RunTappedDensity_default_lifetime_of_execution = timedelta(hours=24)
        self.RunAngleOfRepose_default_lifetime_of_execution = timedelta(hours=24)
        self.RunSingleTest_default_lifetime_of_execution = timedelta(hours=24)
        self.RunManualExperiment_default_lifetime_of_execution = timedelta(hours=24)

    def get_CurrentRun(self, *, metadata: MetadataDict) -> str:
        return self._application.snapshot_json()

    def ClearClog(self, *, metadata: MetadataDict) -> ClearClog_Responses:
        result = self._application.clear_clog()
        return ClearClog_Responses(ResultJson=json.dumps(result, ensure_ascii=False))

    def CaptureCameraPreview(
        self, FocusMode: str, LensPosition: float, *, metadata: MetadataDict
    ) -> CaptureCameraPreview_Responses:
        result = self._application.capture_camera_preview(FocusMode, LensPosition)
        return CaptureCameraPreview_Responses(
            ImageData=result["image_bytes"],
            MediaType="image/jpeg",
            Filename=result["filename"],
        )

    def CaptureReposePreview(self, *, metadata: MetadataDict) -> CaptureReposePreview_Responses:
        result = self._application.capture_repose_preview()
        return CaptureReposePreview_Responses(
            ImageData=result["image_bytes"],
            MediaType="image/png",
            Filename=result["filename"],
        )

    def AbortCurrentOperation(self, *, metadata: MetadataDict) -> AbortCurrentOperation_Responses:
        self._application.abort()
        return AbortCurrentOperation_Responses()

    def SaveResults(self, UpdateMaterialDatabase: bool, *, metadata: MetadataDict) -> SaveResults_Responses:
        self._application.save_pending(
            update_material_database=UpdateMaterialDatabase
        )
        return SaveResults_Responses()

    def DiscardResults(self, *, metadata: MetadataDict) -> DiscardResults_Responses:
        self._application.discard_pending()
        return DiscardResults_Responses()

    def GetSettings(self, *, metadata: MetadataDict) -> GetSettings_Responses:
        return GetSettings_Responses(
            SettingsJson=json.dumps(self._application.get_settings(), ensure_ascii=False)
        )

    def UpdateSettings(self, SettingsJson: str, *, metadata: MetadataDict) -> UpdateSettings_Responses:
        self._application.update_settings(json.loads(SettingsJson))
        return UpdateSettings_Responses()

    def GetMaterialDatabase(self, *, metadata: MetadataDict) -> GetMaterialDatabase_Responses:
        return GetMaterialDatabase_Responses(
            DatabaseJson=json.dumps(
                self._application.get_material_database(), ensure_ascii=False
            )
        )

    def GetArtifact(self, RunId: str, Filename: str, *, metadata: MetadataDict) -> GetArtifact_Responses:
        data, media_type = self._application.get_artifact(RunId, Filename)
        return GetArtifact_Responses(ArtifactData=data, MediaType=media_type)

    @staticmethod
    def _run_observable(instance, intermediate_type, response_type, runner):
        instance.begin_execution()

        def emit(snapshot: dict) -> None:
            instance.progress = float(snapshot.get("progress", 0.0))
            instance.send_intermediate_response(
                intermediate_type(
                    UpdateJson=json.dumps(snapshot, ensure_ascii=False)
                )
            )

        result = runner(emit)
        instance.progress = 1.0
        return response_type(ResultJson=json.dumps(result, ensure_ascii=False))

    def RunAutomatedExperiment(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunAutomatedExperiment_IntermediateResponses],
    ) -> RunAutomatedExperiment_Responses:
        return self._run_observable(
            instance,
            RunAutomatedExperiment_IntermediateResponses,
            RunAutomatedExperiment_Responses,
            self._application.run_automated,
        )

    def RunCalibration(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunCalibration_IntermediateResponses],
    ) -> RunCalibration_Responses:
        return self._run_observable(
            instance,
            RunCalibration_IntermediateResponses,
            RunCalibration_Responses,
            lambda callback: self._application.run_single("calibration", callback),
        )

    def RunBulkDensity(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunBulkDensity_IntermediateResponses],
    ) -> RunBulkDensity_Responses:
        return self._run_observable(
            instance,
            RunBulkDensity_IntermediateResponses,
            RunBulkDensity_Responses,
            lambda callback: self._application.run_single("bulk_density", callback),
        )

    def RunTappedDensity(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunTappedDensity_IntermediateResponses],
    ) -> RunTappedDensity_Responses:
        return self._run_observable(
            instance,
            RunTappedDensity_IntermediateResponses,
            RunTappedDensity_Responses,
            lambda callback: self._application.run_single("tapped_density", callback),
        )

    def RunAngleOfRepose(
        self,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunAngleOfRepose_IntermediateResponses],
    ) -> RunAngleOfRepose_Responses:
        return self._run_observable(
            instance,
            RunAngleOfRepose_IntermediateResponses,
            RunAngleOfRepose_Responses,
            lambda callback: self._application.run_single("angle_of_repose", callback),
        )

    def RunSingleTest(
        self,
        Stage: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunSingleTest_IntermediateResponses],
    ) -> RunSingleTest_Responses:
        return self._run_observable(
            instance,
            RunSingleTest_IntermediateResponses,
            RunSingleTest_Responses,
            lambda callback: self._application.run_single(Stage, callback),
        )

    def RunManualExperiment(
        self,
        VibrationLevel: int,
        VibrationSeconds: float,
        DoseCount: int,
        UseAuger: bool,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstanceWithIntermediateResponses[RunManualExperiment_IntermediateResponses],
    ) -> RunManualExperiment_Responses:
        return self._run_observable(
            instance,
            RunManualExperiment_IntermediateResponses,
            RunManualExperiment_Responses,
            lambda callback: self._application.run_manual(
                vib_level=VibrationLevel,
                vib_seconds=VibrationSeconds,
                dose_count=DoseCount,
                use_aug=UseAuger,
                callback=callback,
            ),
        )
