# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.powdercharacterizercamera import (
    Capture_Responses,
    CaptureRepose_Responses,
    PowderCharacterizerCameraBase,
)

if TYPE_CHECKING:
    from ..server import Server
    from ..drivers.camera import PowderCharacterizerCamera


class PowderCharacterizerCameraImpl(PowderCharacterizerCameraBase):
    def __init__(self, parent_server: Server, driver: PowderCharacterizerCamera) -> None:
        super().__init__(parent_server=parent_server)
        self._driver = driver

    def get_Status(self, *, metadata: MetadataDict) -> str:
        return self._driver.status

    def Capture(
        self, Rotation: int, AutofocusMode: str, LensPosition: float, *, metadata: MetadataDict
    ) -> Capture_Responses:
        image = self._driver.capture(
            rotation=Rotation,
            autofocus_mode=AutofocusMode,
            lens_position=LensPosition if AutofocusMode == "manual" else None,
        )
        return Capture_Responses(
            ImageData=image.data,
            MediaType=image.media_type,
            Filename=image.filename,
            Width=image.width,
            Height=image.height,
        )

    def CaptureRepose(self, *, metadata: MetadataDict) -> CaptureRepose_Responses:
        image = self._driver.capture_repose()
        return CaptureRepose_Responses(
            ImageData=image.data,
            MediaType=image.media_type,
            Filename=image.filename,
            Width=image.width,
            Height=image.height,
        )
