# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.powdercharacterizer_impl import PowderCharacterizerImpl
from .generated.powdercharacterizer import PowderCharacterizerFeature
from .application import PowderCharacterizerApplication


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        application: Optional[PowderCharacterizerApplication] = None,
    ):
        if name is None:
            name = "Powder Characterizer Server"
        if description is None:
            description = (
                "Second-layer Powder Characterizer process server. All physical "
                "operations are delegated to first-layer SiLA 2 servers."
            )
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="PowderCharacterizer",
            server_version="0.1",
            server_vendor_url="https://www.sekisui.com",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.application = application or PowderCharacterizerApplication()
        self.powdercharacterizer = PowderCharacterizerImpl(self, self.application)
        self.set_feature_implementation(PowderCharacterizerFeature, self.powdercharacterizer)
